name: DCPUCraft
main: net.ian.dcpu.DCPUCraft
version: 1.0.0

commands:
    dcpurun:
        description: run the program
        usage: "Usage : /<command>"
        
    dcpustop:
        description: stop the program
        usage: "Usage : /<command>"

    dcpuload:
        description: load the program
        usage: "Usage : /<command>"

    dcpumonitor:
        description: create a monitor
        usage: "Usage : /<command>"  
    dcpu:
        description: create a DCPU with a name
        usage: "Usage : /<command> name"      